# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-Publisher
version:      0.1
version_from: lib/Class/Publisher.pm
installdirs:  site
requires:
    Class::ISA:                    0.32
    Scalar::Util:                  0
    Test::More:                    0.45

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
